# Generated by Django 4.2.30 on 2026-06-02 19:15

from django.db import migrations

def delete_non_amazon_flipkart_products(apps, schema_editor):
    Product = apps.get_model('ecom', 'Product')
    OrderItem = apps.get_model('ecom', 'OrderItem')
    Order = apps.get_model('ecom', 'Order')
    CartItem = apps.get_model('ecom', 'CartItem')

    # Find products that are NOT Amazon or Flipkart
    non_target_products = Product.objects.exclude(brand__in=['Amazon', 'Flipkart'])

    # Delete CartItems referencing these products
    CartItem.objects.filter(product__in=non_target_products).delete()

    # Delete OrderItems and associated Orders referencing these products
    order_items_to_delete = OrderItem.objects.filter(product__in=non_target_products)
    orders_to_delete_ids = list(order_items_to_delete.values_list('order', flat=True).distinct())

    order_items_to_delete.delete()
    Order.objects.filter(id__in=orders_to_delete_ids).delete()

    # Delete the products themselves
    non_target_products.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_non_amazon_flipkart_products),
    ]

