# Generated by Django 4.2.30 on 2026-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
