# Generated by Django 4.2.30 on 2026-04-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_voucher_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='image_url',
        ),
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
