# Generated by Django 4.2.30 on 2026-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_voucher_image_url_voucher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='icon',
            field=models.CharField(default='🎫', help_text='Emoji fallback', max_length=8),
        ),
    ]
