# Generated by Django 4.2.27 on 2026-04-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_voucher_category_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='category',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='category_rel',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='store.category'),
        ),
    ]
